export const featuredEvents = [
    {
      id: 1,
      title: "Hack the Future 2024",
      description: "Join us for a 24-hour hackathon where you'll build innovative solutions to real-world problems.",
      image: "/placeholder.svg?height=300&width=500&text=Hackathon",
      date: "15 Mar, 2024",
      location: "MIT Campus",
      attendees: 250,
      category: "Hackathon",
    },
    {
      id: 2,
      title: "Web Dev Workshop",
      description: "Learn the latest web development technologies in this hands-on workshop.",
      image: "/placeholder.svg?height=300&width=500&text=Workshop",
      date: "18 Mar, 2024",
      location: "Stanford Campus",
      attendees: 120,
      category: "Workshop",
    },
    {
      id: 3,
      title: "AI Revolution Talk",
      description: "Discover how AI is transforming industries in this insightful tech talk.",
      image: "/placeholder.svg?height=300&width=500&text=Tech+Talk",
      date: "20 Mar, 2024",
      location: "Harvard Campus",
      attendees: 180,
      category: "Tech Talk",
    },
    {
      id: 4,
      title: "Blockchain Bootcamp",
      description: "Immerse yourself in blockchain technology and cryptocurrency development.",
      image: "/placeholder.svg?height=300&width=500&text=Bootcamp",
      date: "22 Mar, 2024",
      location: "UC Berkeley",
      attendees: 90,
      category: "Workshop",
    },
    {
      id: 5,
      title: "Design Thinking Masterclass",
      description: "Learn how to apply design thinking principles to solve complex problems.",
      image: "/placeholder.svg?height=300&width=500&text=Masterclass",
      date: "25 Mar, 2024",
      location: "Stanford Campus",
      attendees: 75,
      category: "Workshop",
    },
    {
      id: 6,
      title: "Startup Networking Mixer",
      description: "Connect with founders, investors, and tech enthusiasts in this casual networking event.",
      image: "/placeholder.svg?height=300&width=500&text=Networking",
      date: "28 Mar, 2024",
      location: "MIT Campus",
      attendees: 150,
      category: "Networking",
    },
  ]